---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  build.image:
    dir: images/apko
    sources:
      - apko.yaml
    cmds:
      - for: sources
        cmd: apko build {{.ITEM}} apko:{{.APKO_VERSION}} apko-{{.APKO_VERSION}}.tar
    preconditions:
      - sh: which apko
        msg: "apko is not installed. Please install apko."

  load.image:
    desc: Load apko container image
    dir: images/apko
    cmds:
      - docker load -i apko-{{.APKO_VERSION}}.tar
    preconditions:
      - sh: test -f apko-{{.APKO_VERSION}}.tar
        msg: "apko container image not found. Please build it first."

  publish.image:
    desc: Using apko to publish image to registry
    dir: images/apko
    cmds:
      - apko publish apko.yaml {{.GITHUB_REGISTRY}}/apko:{{.APKO_VERSION}}

  tag.image:
    desc: Tag apko container image
    vars:
      ARCH:
        sh: uname -m
    cmds:
      - docker tag apko:{{.APKO_VERSION}}-{{.ARCH}} {{.GITHUB_REGISTRY}}/apko:{{.APKO_VERSION}}

  run.image:
    desc: Run apko container image
    cmds:
      - docker run --rm -it apko:{{.APKO_VERSION}}-{{.ARCH}}
    preconditions:
      - sh: which docker
        msg: "Docker is not installed. Please install Docker."
