---
area/docs:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"
area/workflows:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/*.yaml"
area/config:
  - changed-files:
      - any-glob-to-any-file:
          - ".mise/**"
          - ".lefthook.yaml"
          - ".github/renovate.json"
area/container:
  - changed-files:
      - any-glob-to-any-file: "images/**"
area/ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/image-filters.yaml"
          - "images/*/tests/**"
          - "images/base/tests.yaml"
