---
defaultIgnores: true
rules:
  type-enum:
    - 2
    - always
    - - build
      - chore
      - ci
      - docs
      - feat
      - fix
      - perf
      - refactor
      - revert
      - style
      - test
  type-case:
    - 2
    - always
    - lower-case
  subject-empty:
    - 2
    - never
  header-max-length:
    - 2
    - always
    - 72
  body-max-line-length:
    - 0
    - always
    - 100
  subject-case:
    - 2
    - never
    - - pascal-case
      - start-case
      - upper-case
