---
assert_lefthook_installed: true
skip_lfs: true

prepare-commit-msg:
  commands:
    commitzen:
      interactive: true
      run: bash -lc 'cz check --message "$(cat {1})"'
      env:
        LEFTHOOK: "0"

commit-msg:
  commands:
    "lint commit message":
      run: commitlint --edit {1}

pre-commit:
  parallel: true
  jobs:
    - name: format yaml
      glob: "*.yaml"
      run: yamlfmt {staged_files}
      tags:
        - format
      stage_fixed: true

    - name: check links
      tags:
        - docs
      run: lychee --max-concurrency 3 {staged_files}
      glob: '*.md'
      exclude:
        - CHANGELOG.md

    - name: format markdown
      glob: "*.md"
      run: prettier --write {staged_files}
      tags:
        - docs
      stage_fixed: true

    - name: fix typos
      tags:
        - lint
      run: typos --write-changes {staged_files}
      stage_fixed: true

