---
version: "0.2"
language: en_US
caseSensitive: false
dictionaries:
  - en_US
  - companies
  - softwareTerms
  - misc
  - go
  - python
  - bash
words:
  - addler
  - admissionregistration
  - apeiros
  - apiextensions
  - apiserver
  - apiservers
  - apiservice
  - apko
  - approle
  - aquasec
  - archs
  - Automerge
  - awsuswest
  - bargauge
  - behaviour
  - beholdenkey
  - Beyla
  - cadvisor
  - certmanager
  - certmanagerconfig
  - certwatcher
  - chainguard
  - cloudnative
  - clustername
  - clusterrole
  - clusterrolebinding
  - clusterrolebindings
  - clusterroles
  - compositeresourcedefinition
  - compositeresourcedefinitions
  - Containeer
  - CONTROLPLANE
  - controlplanes
  - Coredns
  - cpus
  - CPUS
  - crds
  - creds
  - crossplane
  - customresource
  - customresourcedefinitions
  - datasource
  - datawave
  - delelete
  - deleleted
  - depguard
  - distroless
  - dotenv
  - envcfg
  - environmentconfig
  - environmentconfigs
  - errorf
  - finalizers
  - Fluentbit
  - fluxcd
  - forbidigo
  - forgelabs
  - FOWNER
  - gitops
  - gnet
  - gocritic
  - gofumpt
  - goheader
  - GOMAXPROCS
  - GOMEMLIMIT
  - goroutines
  - groupname
  - gruntwork
  - htttps
  - hyperscaler
  - Hyperscaler
  - imagesafe
  - incluster
  - ingresscert
  - inotify
  - Invocatios
  - ipairs
  - jsonnet
  - kpfnk
  - Kubebuilder
  - kubeconfig
  - Kubelet
  - Kyverno
  - lameduck
  - loadbalance
  - managedresource
  - markdownlint
  - markus
  - mayastor
  - memstats
  - metricsserver
  - mjmc
  - moa
  - moaas
  - mrvsn
  - Multus
  - mutatingwebhookconfigurations
  - nfscsi
  - nfscsiconfig
  - nfsvers
  - nonroot
  - NOTHANKS
  - nzhjh
  - opencontainers
  - openebs
  - openebses
  - opentofu
  - osss
  - perfsprint
  - podinfo
  - providerrevisions
  - Pulumi
  - Pyroscope
  - Quentile
  - readyz
  - resolv
  - rgba
  - rolebindings
  - Rollouts
  - schweig
  - seccomp
  - serviceaccounts
  - servicelb
  - SETGID
  - siderolabs
  - smartquotes
  - Solidtime
  - Spegel
  - sprintf
  - staticcheck
  - stdlib
  - strconcat
  - submatches
  - talosconfig
  - talosctl
  - taskfile
  - Taskfile
  - taskfiles
  - terragrunt
  - testifylint
  - tfstate
  - thelper
  - timepicker
  - tparallel
  - Tradecraft
  - traefik
  - trufflehog
  - trufflesecurity
  - upbound
  - upjet
  - uptest
  - UPTEST
  - validatingwebhookconfigurations
  - vcluster
  - Virt
  - Volsync
  - wolfi
  - workqueue
  - wsize
  - xargocd
  - xcertmanager
  - xcertmanagerconfig
  - xcilium
  - xcoredns
  - xdns
  - xflux
  - xharbor
  - xmetrics
  - xmetricsserver
  - xnfscsi
  - xnfscsiconfig
  - xopenebs
  - xosss
  - xpkg
  - xpodinfo
  - xrds
  - xxcoredns
  - yamlfmt
  - Zitadel
  - Trimpath
  - ldflags
  - Ldflags
  - trimpath
  - codegen
  - iface
  - Estar
  - Mediatypes
  - Ocimedia
  - TRACEPARENT
  - querybuilder
  - gqlgen
  - errgroup
  - QLID
  - gctx
  - genqlient
  - callpbv
  - nolint
  - gosec
  - sdklog
  - sdktrace
  - otlplog
  - otlploggrpc
  - otlploghttp
  - otlpmetric
  - otlpmetricgrpc
  - otlpmetrichttp
  - otlptrace
  - otlptracegrpc
  - otlptracehttp
  - sdkmetric
  - semconv
  - dupl
  - otlptracehttp
  - otlpmetricgrpc
  - otlpmetrichttp
  - iostat
  - readbytes
  - writebytes
  - cpustat
  - UCUM
  - rerr
  - metricdata
  - collogspb
  - otlpcommonv
  - otlplogsv
  - otlpmetricsv
  - otlpresourcev
  - otlptracev
  - BOOLSLICE
  - STRINGSLICE
  - sctx
  - Kvlist
  - ungeneric
  - ehdp
