---
version: "3"

set:
  - pipefail
shopt:
  - globstar

includes:
  workstation:
    taskfile: .taskfiles/Workstation/Taskfile.yaml
    flatten: true
tasks:
  default:
    desc: Show help
    cmds:
      - task --list
