---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  build.image:
    dir: images/jellyfin
    sources:
      - apko.yaml
    cmds:
      - for: sources
        cmd: apko build {{.ITEM}} jellyfin:{{.JELLYFIN_VERSION}} jellyfin-{{.JELLYFIN_VERSION}}.tar
    preconditions:
      - sh: which apko
        msg: "apko is not installed. Please install apko."

  load.image:
    desc: Load jellyfin container image
    dir: images/jellyfin
    cmds:
      - docker load -i jellyfin-{{.JELLYFIN_VERSION}}.tar
    preconditions:
      - sh: test -f jellyfin-{{.JELLYFIN_VERSION}}.tar
        msg: "jellyfin container image not found. Please build it first."

  publish.image:
    desc: Using apko to publish image to registry
    dir: images/jellyfin
    cmds:
      - apko publish apko.yaml {{.GITHUB_REGISTRY}}/jellyfin:{{.JELLYFIN_VERSION}}

  tag.image:
    desc: Tag jellyfin container image
    vars:
      ARCH:
        sh: uname -m
    cmds:
      - docker tag jellyfin:{{.JELLYFIN_VERSION}}-{{.ARCH}} {{.GITHUB_REGISTRY}}/jellyfin:{{.JELLYFIN_VERSION}}

  run.image:
    desc: Run jellyfin container image
    cmds:
      - docker run --rm -it jellyfin:{{.JELLYFIN_VERSION}}-{{.ARCH}}
    preconditions:
      - sh: which docker
        msg: "Docker is not installed. Please install Docker."
