---
name: "Bug Report"
description: "Submit a report to help us improve."
title: "Bug: [Enter a descriptive title]"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Reporting Guide

        Please follow these guidelines to streamline the issue resolution process:

        - **Search** for similar issues before creating a new one.
        - **Provide** clear and detailed information to help us reproduce and understand the problem.
        - **Consider** the potential security and operational impacts.

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the bug in detail."
      placeholder: "A clear and concise description of what the bug is."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: "Reproduction Steps"
      render: Shell
      description: "Provide the steps to reproduce the issue."
      placeholder: "Steps to reproduce the behavior."
      value: |
        ...
    validations:
      required: true

  - type: textarea
    id: severity
    attributes:
      label: "Severity"
      description: "Indicate the impact level of the bug (e.g., low, medium, high, critical)."
      placeholder: "Impact severity."

  - type: textarea
    id: os
    attributes:
      label: "OS / Environment"
      description: "Provide details about the operating system, environment, or network setup."
      placeholder: "OS / Environment details."

  - type: textarea
    id: additional
    attributes:
      label: "Additional Information"
      description: "Include any extra details such as logs, software versions, screenshots, etc."
      placeholder: "Additional information."
