---
name: "New Container Image"
description: "Request a new container image to be supported"
title: "Feature: [Enter a descriptive title]"
labels:
  - "enhancement"
  - "feature request"
assignees: "beholdenkey"
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request Guidelines

        Please follow these guidelines to help us evaluate and implement your request effectively:

        - **Check** if a similar feature request already exists.
        - **Describe** what the feature will bring to the project or community.
        - **Define** clear acceptance criteria.
        - **Consider** potential security, compliance, and scalability impacts.
        - **Participate** in discussions for clarifications and follow-up.

  - type: textarea
    id: description
    attributes:
      label: "Detailed Description"
      description: "Provide a detailed description of the new container image request."
      placeholder: "Enter the detailed description here"
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Provide any additional context or information that might be useful."
      placeholder: "Enter any additional context here"
    validations:
      required: false
